// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDksJN_OOPMTVAAfwVDqItgMSNcIa6RBYw',
    appId: '1:930521539212:web:380ba8723d3dfbffb191a9',
    messagingSenderId: '930521539212',
    projectId: 'lapr-chat',
    authDomain: 'lapr-chat.firebaseapp.com',
    storageBucket: 'lapr-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt2y9stgF0kr8rgcjdWV4QRNhvyprKIgU',
    appId: '1:930521539212:android:4094182c9aa6663cb191a9',
    messagingSenderId: '930521539212',
    projectId: 'lapr-chat',
    storageBucket: 'lapr-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSM6iHiJZEG4YI47w5fEct7yjiYuIU3PY',
    appId: '1:930521539212:ios:4482091f68fe58d4b191a9',
    messagingSenderId: '930521539212',
    projectId: 'lapr-chat',
    storageBucket: 'lapr-chat.appspot.com',
    iosBundleId: 'com.example.laprChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSM6iHiJZEG4YI47w5fEct7yjiYuIU3PY',
    appId: '1:930521539212:ios:4482091f68fe58d4b191a9',
    messagingSenderId: '930521539212',
    projectId: 'lapr-chat',
    storageBucket: 'lapr-chat.appspot.com',
    iosBundleId: 'com.example.laprChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDksJN_OOPMTVAAfwVDqItgMSNcIa6RBYw',
    appId: '1:930521539212:web:477f61f78d797716b191a9',
    messagingSenderId: '930521539212',
    projectId: 'lapr-chat',
    authDomain: 'lapr-chat.firebaseapp.com',
    storageBucket: 'lapr-chat.appspot.com',
  );
}
